### ISSUE TITLE
Sporadic extreme slowdowns in deep detachment after settling for very long time

### ISSUE THREAD

**Issue by mikekryjak** [bendudson/hermes-3#198]
Thanks to Matt Khan for spotting this in his simulations and doing the initial debugging.

Our 1D STEP simulations in deep detachment (10m from target) slow down substantially upon front movement when very near steady state. This seems to appear only when the simulation has run for hundreds of ms to the point where each front movement is 100s of ms apart, and does not happen earlier in the simulation where the front easily jumps from cell to cell in the same domain region without issue.

The symptom is an extremely long iteration (10hrs vs. typical 3min on 40 cores) just before front movement.

Here is a decomposition of ddt() components around the time of the spike. The front movement happens in the final spike in residuals, but the wall time spike happens just before. There doesn't appear to be any helpful pattern to this:
![image](https://github.com/bendudson/hermes-3/assets/62797494/ee8826b8-633f-4633-8f55-8130cdf2d8c2)

I have plotted profiles at several timeslices and found nothing special about this particular front jump:
![image](https://github.com/bendudson/hermes-3/assets/62797494/4663f043-19de-4c90-ac57-8d83e545dd41)
![image](https://github.com/bendudson/hermes-3/assets/62797494/c112649a-3dd0-41af-89bb-4da6fae42b30)
![image](https://github.com/bendudson/hermes-3/assets/62797494/ec177d5d-9bee-4c1f-a894-20e2f31741a4)

I have also plotted the domain integral histories of the atomic and impurity radiation reactions. It tells us nothing new apart from that the hydrogenic reactions are changing rapidly during the slowdown (but almost as rapidly before it and more rapidly afterwards). Reaction rates are highly nonlinear but do not feature a preconditioner, so they could cause poor performance. However, they move a lot every time the front jumps, and there is no issue in the simulation until far into the steady state.
![image](https://github.com/bendudson/hermes-3/assets/62797494/50d7de31-f7ab-4dd7-9059-6558267ad940)

Diagnosing CVODE shows a spike in the number of fails and a drop in the linear to nonlinear iteration ratio. This (I think) means that nonlinear iterations keep failing which makes CVODE reduce timestep to extremely low levels resulting in the very long iteration. The order drops to 1 so this isn't connected with CVODE's sporadic hogging of higher orders at low timesteps. I am not sure if there's anything in here that would warrant a change in solver settings.

![image](https://github.com/bendudson/hermes-3/assets/62797494/54261490-1760-40f0-bdc6-ac047fbc866b)

I have done a test where I restarted the simulation from just before the spike to see if the issue is caused by the CVODE algorithm tuning its settings for the long quiescent period and then being "surprised" by the spike (thanks for the idea @bendudson). Unfortunately the spike happens in the same way as before. The next step is to significantly reduce timestep size and rerun the simulation to get a better handle of what dynamics are connected with the spike (current timestep is 5ms).

**Comment by mikekryjak** [comment]
This could be caused by a non-monotonic jump in the coulomb Logarithm. Thanks to Stefan Mijin for identifying this in ReMKiT1D. 

![image](https://github.com/bendudson/hermes-3/assets/62797494/23f78d07-d707-4058-9e4b-adeb23e02cd9)

**Comment by mikekryjak** [comment]
Now fixed in ReMKiT1D:

https://github.com/ukaea/ReMKiT1D/commit/a6a17b876afa67918329d1599fbdf41262604822

**Comment by PoloidalLloyd** [comment]
This issue has been resolved by commit [ae72a05](https://github.com/boutproject/hermes-3/commit/ae72a05a178987968c8a18944fe178740f8fd711)

**Comment by mikekryjak** [comment]
I need to try and reproduce the slowdown again. I think I still have the case.
